### ISSUE TITLE
QUESTION: Parenting bodies

### ISSUE THREAD

**Issue by edunad** [Sopiro/Muli#1]
First of all, amazing work so far <3.

I was wondering if there is support for parenting bodies with a stiff connection (not welding).

Currently in the game we want to be able to move props (bodies) inside of a ship, but have the ship move all the bodies inside of it (parented). 

Kinda how unity does transforms :
![image](https://user-images.githubusercontent.com/4944278/223725602-c579542a-6d1c-4903-9715-e035a96b1291.png)

Maybe a container body type? That acts as a sub-world

**Comment by Sopiro** [comment]
The feature you want looks like scene hierarchy. I think this is more of a game engine feature than a physics engine feature.

You can implement this like after a physics update, recursively reposition the child's transform relative to the parent's local transform (which is registerd in physics engine).

Check out this article!: https://learnopengl.com/Guest-Articles/2021/Scene/Scene-Graph

**Comment by edunad** [comment]
> The feature you want looks like scene hierarchy. I think this is more of a game engine feature than a physics engine feature.
> 
> You can implement this like after a physics update, recursively reposition the child's transform relative to the parent's local transform (which is registerd in physics engine).
> 
> Check out this article!: https://learnopengl.com/Guest-Articles/2021/Scene/Scene-Graph

Will take a look :D, thanks!
