### ISSUE TITLE
Build failing on latest version in linux

### ISSUE THREAD

**Issue by edunad** [Sopiro/Muli#3]
After updating muli, the build on linux is now throwing a error:
"fatal error: format: No such file or directory"

It seems to only be supported on gcc > 13.1, but the current linux LTS only supports up to 12 :(

![image](https://github.com/user-attachments/assets/98063a27-3214-49ba-8b99-7e84dfe4dcd5)
https://github.com/edunad/rawrbox/actions/runs/10596571729/job/29364824119#step:6:1817

An alternative to fix this would be to use [FMT](https://github.com/fmtlib/fmt)

**Comment by Sopiro** [comment]
Sorry for the late reply. I’ve also experienced the same error with GitHub Actions.

If you use ubuntu-24.04 instead of ubuntu-latest, as shown here 

https://github.com/Sopiro/Muli/blob/master/.github/workflows/cmake-multi-platform.yml#L26

 the build will work.

**Comment by edunad** [comment]
> Sorry for the late reply. I’ve also experienced the same error with GitHub Actions.
> 
> If you use ubuntu-24.04 instead of ubuntu-latest, as shown here
> 
> https://github.com/Sopiro/Muli/blob/master/.github/workflows/cmake-multi-platform.yml#L26
> 
> the build will work.

No worries, sadly self-hosted runners only support 22.04 actions, 24.04 is not out yet :(

**Comment by Sopiro** [comment]
Hi, I’ve removed the std::format dependencies, so the build should now work!
